language: bash
services: docker

install:
  - git clone https://github.com/junhuqc/docker_golang_nodejs.git

before_script:
  - cd docker_golang_nodejs

script:
  - docker build -t "agendolabs/golang_nodejs" .

after_script:
  - docker images